### ISSUE TITLE
Choose hours

### ISSUE THREAD

**Issue by raphaelgolin** [lukevella/Rallly#24] opened 2016-11-07 18:06 UTC
First of all, great jog. The platform is super cool, beautiful, and usefull.

My issue is: is there any way to set a time gap instead of a hole day?
I mean, my meetings never last all day, and sometimes I have 2 or 3 meetings in one single day. Would be very useful if I could set a time window in a day the i`m free for meetings, lets say Monday at 10h to 12h.

Thanks in advance, and great job!

**Comment by lukevella** [comment] 2017-01-24 19:21
Duplicate of #4. Closing.

**Closed by lukevella** 2017-01-24 19:21 UTC
