### ISSUE TITLE
Feature request : Prevent participants from being able to modify other participants selections

### ISSUE THREAD

**Issue by gene1wood** [lukevella/rallly#129] opened 2022-04-22 17:22 UTC
# Steps to reproduce

1. Create a poll in browser A
2. Copy and paste the participant share link from the admin UI in browser A into browser B to simulate being a participant
3. In browser B fill out that participants selections for the dates and times that work for them
4. Copy and paste the participant share link from the admin UI in browser A into browser C to simulate being a different participant

# Expected results

The participant in browser C can't edit the other participant's selections. 

This is achieved by something like a cookie being set in browser B when the first participant chooses their dates/times. If that participant returns in the same browser they can edit their entry.

If a different participant visits the participant link and has no cookie because they've never filled out the form, they don't have an option to edit a different participants choices

# Actual results

The participant in browser C can modify any other participant's choices.

**Comment by lukevella** [comment] 2022-04-23 10:28
Duplicate of #124

**Closed by lukevella** 2022-04-23 10:28 UTC
