### ISSUE TITLE
Bug: selected dates show differently for different users

### ISSUE THREAD

**Issue by aminah-sc** [lukevella/rallly#61] opened 2018-08-22 12:17 UTC
Selected date options do not appear to be completely synchronised with all other participants.

The example below are screenshots of _exactly_ the same board from two different users (one having selected 22nd Aug, but shows as 23rd Aug for the other):

![image](https://user-images.githubusercontent.com/36522678/44462510-b584d580-a60c-11e8-8af6-64affe8d1f83.png)

![image](https://user-images.githubusercontent.com/36522678/44462551-d5b49480-a60c-11e8-8e55-ca61c263099a.png)

**Comment by egcohen** [comment] 2019-09-17 03:48
This is a duplicate of bug #22, and it still hasn't been fixed.

**Comment by fsut** [comment] 2020-12-02 23:01
Hello,

I just came across this issues myself. It has been showing differently on my computer and on my phone.
Could you please have a look at this? It pretty much disqualifies this app from being used although it appeared really nice and useful when I came across it.

Thank you.

**Comment by lukevella** [comment] 2022-04-12 12:31
Fixed in the new version. Note legacy polls that have been transferred over will still have the same issue. It is to do the fact that dates were stored with time zone information when they should not have been.

**Closed by lukevella** 2022-04-12 12:31 UTC
