### ISSUE TITLE
Login page doesn't work

### ISSUE THREAD

**Issue by Ehtor** [lukevella/rallly#690] opened 2023-05-09 21:52 UTC
**Describe the bug**
Selfhosting a instance of rallly and everytime I want to register a new user I get the code via mail but if I type it in it brings me back to the login mask. Trying to login with that user you also get the code via mail but nothing happens when you click on next. If I click the Autologin Button in the mail, I get a login affirmation site which redirects me to the login form.

**To Reproduce**
5. Create a new user
6. Verify the new user
7. Be stuck on the login page

**Expected behavior**
Be not stuck on the login page ;)

**Comment by lukevella** [comment] 2023-05-09 22:04
It sounds like you're using a reverse proxy in front of the app and it's not configured to forward the headers to the server. There's some example configs here that might help:

https://github.com/lukevella/rallly-selfhosted/tree/main/reverse-proxy

I'm closing this since it's almost certainly not a bug but let me know if there's anything else.

**Closed by lukevella** 2023-05-09 22:04 UTC

**Comment by Ehtor** [comment] 2023-05-09 22:14
Hey, thank you but no reverse proxy right now. Just deployed the container without any additional modifications in my local network. I used different browsers and went through the logs. They give me absolutely no feedback about the login activity.

**Comment by lukevella** [comment] 2023-05-09 22:21
Ok that probably means that `NEXT_PUBLIC_BASE_URL` is not configured correctly. If you're accessing the container directly it's probably going to need to be set to `http://localhost:3000`. Check the network tab of your browser to see what requests are failing and why. It sounds like they're not reaching the server.

**Comment by Ehtor** [comment] 2023-05-09 23:29
I only get Code 200s, nothing unexpected. Tried setting localhost and the servers IP address. Same error.

**Comment by svseidel** [comment] 2023-05-10 05:39
With  the same setup I have the same problem.

**Comment by Nuuki9** [comment] 2023-05-16 08:28
Here's a quick example video. I've left the network tab open but not sure if you'll see enough to be useful. If you need a full export from that or other tabs let me know. No errors in the container's logs.

[Example.webm](https://github.com/lukevella/rallly/assets/30313491/548f7499-a58c-4af2-9f5c-71d2c3cc0b6f)

I can try it with the proxy later on if you think that will provide a useful data point. I did try from multiple browsers though.

**Comment by lukevella** [comment] 2023-05-16 08:52
Can you check if the cookie is being set under Application > Cookies in the the dev panel?

**Comment by Nuuki9** [comment] 2023-05-16 09:02
Cookies are not being blocked:

<img width="238" alt="image" src="https://github.com/lukevella/rallly/assets/30313491/6875a090-7413-41e6-8e98-89c3ec167758">

I do see a Rallly session cookie being set:

<img width="293" alt="image" src="https://github.com/lukevella/rallly/assets/30313491/23868058-4657-4fab-9e42-75a3c0b7edfc">

**Comment by lukevella** [comment] 2023-05-16 09:04
So if you visit another page, are you logged in? Is it just the redirect that's not working for you?

**Comment by Nuuki9** [comment] 2023-05-16 09:25
I have now tried it behind a reverse proxy and it is indeed working.

When I was unable to login I of course didn't have a page to try, but now that I can, I can see pages at `/new` and `/profile`. So if I switch back I could try those pages directly in case its just the redirect which isn't working.

As its working for me with the proxy I'm probably fine, though happy to do a further test if it helps.
