### ISSUE TITLE
When editing date/time entries: Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by adamzmoravy** [lukevella/rallly#929] opened 2023-11-06 13:32 UTC
**Describe the bug**
2 bugs actually.I created a poll, then wanted to add some dates. That didn't work (when saved, the dates didn't propagate) - 1st bug. So I've tried to add times to time entries, that worked. Then I tried to delete times and leave only dates again and then the bug appeared - 2nd bug.

**To Reproduce**
1. Add new poll
2. Edit the poll - add new dates
3. 1st bug - the dates are not added
4.  Add time entries and new dates via edit options
5.  Edit options again - remove times from dates
6. 2nd bug (as seen on screen bellow) appeared
7. Now I can't edit or view poll

**Expected behavior**
In 1st case - dates should be added. 2nd bug - error

**Screenshots**
<img width="1602" alt="image" src="https://github.com/lukevella/rallly/assets/1129007/65a4c96c-6153-43b0-bfc5-90bdc4a824eb">

**Desktop:**
 - OS: macOS 14.1 (23B74)
 - Browser: Arc
 - Version: 1.15.1 (43023)

**Comment by 18feb06** [comment] 2023-11-07 13:20
I tried but I was not able to reproduce

**Comment by lukevella** [comment] 2023-11-07 13:31
Hi @adamzmoravy, there was a bug that would have caused this when trying to replace all the dates in a poll. I believe this should be fixed now so I’ll close this. Feel free to reopen if it’s not fixed for you.

**Closed by lukevella** 2023-11-07 13:31 UTC
