### ISSUE TITLE
Login via magic link not working

### ISSUE THREAD

**Issue by janru** [lukevella/rallly#285] opened 2022-08-12 22:44 UTC
**Description**
Login with magic link does not work. After reloading the page, there's still no cookie set and a new user name appears (e.g. "user-ab123").

**To Reproduce**
1. setup ToT version rallly with docker-compose ( I use 3333:3000 in docker compose config, could this be an issue?!)
2. Go to hosted Rallly domain
3. Click on 'Get Started' / '3 dot icon next to user' / 'Login'
4. Copy magic link and open in same browser (no cookie blocking active, tried with 5 browsers,  see below)
5. Reload Website multiple times. Each time, a different user name appears and there is no cookie set.

**Expected behavior**
When reloading the page after login, the user name should stay consistent and it should be possible to e.g. change the votes.

**Screenshots**
![image](https://user-images.githubusercontent.com/5803281/184453261-6e9e4970-97ec-4295-841f-57d14bc9ac83.png)

**Desktop:**
 - OS: Arch Linux
 - Browser Chromium (Version 103.0.5060.134 (Official Build) Arch Linux (64-bit)), Vivaldi (5.3.2679.70 (Stable channel) stable (64-bit) ), Firefox
 - Version latest, each

**Smartphone:**
 - Device: Pixel 6
 - OS: Android 12
 - Browser Vivaldi, Chrome
 - Version latest

**Comment by lukevella** [comment] 2022-08-16 08:44
Hi @janru, a few things to check:

* How are you accessing the app? Directly via localhost? Using a reverse proxy? What domain?
* Did you set `NEXT_PUBLIC_BASE_URL` to the domain you use to access the app?
* It sounds perhaps like the cookie is either being set on a different domain or not being set at all. This is likely to be a misconfiguration from your end though as it clearly works on rallly.co.

I'm closing this issue since I can't reproduce it. If you need further support I'd recommend joining our [discord](https://discord.gg/uzg4ZcHbuM).

**Closed by lukevella** 2022-08-16 08:44 UTC
Labels: bug

**Comment by janru** [comment] 2022-08-16 17:08
Issue is resolved. I added a nginx reverse proxy and the magic links work as expected.
