### ISSUE TITLE
v3 share link does not use NEXT_PUBLIC_BASE_URL

### ISSUE THREAD

**Issue by TheZoker** [lukevella/rallly#848] opened 2023-09-12 10:52 UTC
**Describe the bug**
When I create a new poll in version 3, the share link looks like this:
![image](https://github.com/lukevella/rallly/assets/1368405/c5c7d4fd-a3f2-4540-9548-a2c30e69daa1)

**To Reproduce**
1. Create a new poll
2. Share it

**Expected behavior**
Use the `NEXT_PUBLIC_BASE_URL` env variable for the share url 

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: v1.57.62

**Comment by TheZoker** [comment] 2023-09-12 11:00
In the sent email the link is displayed correctly

**Comment by lukevella** [comment] 2023-09-12 11:02
Thanks for reporting. I've had a look and it appears the issue is because  the value of `NEXT_PUBLIC_BASE_URL` is being used at build time here which is not correct. I'll push a temporary fix for this that uses `window.location.origin` as the base URL which is how it worked previously but it may be worth considering using something like [next-runtime-env](https://github.com/expatfile/next-runtime-env) to solve this issue.

**Closed** 2023-09-12 11:17 UTC

**Comment by lukevella** [comment] 2023-09-12 11:21
@TheZoker, fix should be available now if you can pull the image again and restart.

**Comment by TheZoker** [comment] 2023-09-12 11:33
Yes can confirm this works, thanks 🎉
