### ISSUE TITLE
Screen reader accessibility

### ISSUE THREAD

**Issue by LizHareDogs** [lukevella/rallly#1396] opened 2024-10-14 14:28 UTC
Hi, I found Rallly in my search for a meeting pool that I can use with a screen reader. I can't use most of them. Rallly looks like what I need in lots of ways: it's a streamlined interface that lets me do exactly what I need to do when working with international teams.

I use a Mac with the native VoiceOver screen reader. I tried in Safari first, and I wasn't able to select times in the view that shows the list of times in a day. The times look like plain text to the screen reader and not something that can be selected. I tried making selections and them submitting the form but I got an error telling me I had to select options.

I tried the same form also in Firefox, and there were menus that I either couldn't open or couldn't interact with the choices. I wasn't able to log in by changing from "guest" (because I was in a new browser)

**Comment by lukevella** [comment] 2024-10-21 15:52
Hey @LizHareDogs. I'm sorry for the poor user experience. There's still a lot of work to be done in this area and I'll be addressing it gradually with new and updated designs that make accessibility a priority. I'll close this as it's a duplicate of #306

**Closed by lukevella** 2024-10-21 15:52 UTC
