### ISSUE TITLE
OIDC Login not working with Authelia

### ISSUE THREAD

**Issue by thamudi** [lukevella/rallly#979] opened 2024-01-14 14:06 UTC
**Describe the bug**
I am unable to see the OIDC login option [after setting up the OIDC following the steps here](https://support.rallly.co/self-hosting/single-sign-on)

**To Reproduce**
1. Setup Rallly with OIDC
Set these env vars:
```env
  OIDC_ENABLED: "true"
  OIDC_NAME: "OIDC"
  OIDC_CLIENT_ID: rally
  OIDC_CLIENT_ID: <redacted>
  OIDC_DISCOVERY_URL: "https://auth.example.ngo/.well-known/openid-configuration"
```
2. Go to login screen.
3. No login button with OIDC option is visible.

**Expected behavior**
To see the login with OIDC button.

**Screenshots**
![image](https://github.com/lukevella/rallly/assets/18720062/454ee245-5b66-4ff5-b217-214157460f15)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome, Firefox
 - Version v3.5.0

**Additional context**
Nothing is shown in the logs for this matter. And for additional context we are running the stable docker image.

**Comment by sjthiessen** [comment] 2024-01-15 15:33
I had the same issue. Have you tried checking whether your envs in your container meet the requirements?
https://github.com/lukevella/rallly/blob/c2fc3a5fac1c011f7b228c642166d7e4faa8b7a3/apps/web/src/utils/constants.ts#L16

For me it was the secret I didn't set properly

**Comment by lukevella** [comment] 2024-01-15 15:55
> ```dotenv
>   OIDC_ENABLED: "true"
>   OIDC_NAME: "OIDC"
>   OIDC_CLIENT_ID: rally
>   OIDC_CLIENT_ID: <redacted>
>   OIDC_DISCOVERY_URL: "https://auth.example.ngo/.well-known/openid-configuration"
> ```

Indeed from the above it appears that `OIDC_CLIENT_SECRET` is missing and `OIDC_CLIENT_ID` was set twice. I'm assuming this is the problem so I'm closing this but feel free to reopen if that's not the case.

**Closed by lukevella** 2024-01-15 15:55 UTC

**Comment by thamudi** [comment] 2024-01-16 11:35
> > ```dotenv
> >   OIDC_ENABLED: "true"
> >   OIDC_NAME: "OIDC"
> >   OIDC_CLIENT_ID: rally
> >   OIDC_CLIENT_ID: <redacted>
> >   OIDC_DISCOVERY_URL: "https://auth.example.ngo/.well-known/openid-configuration"
> > ```
> 
> Indeed from the above it appears that `OIDC_CLIENT_SECRET` is missing and `OIDC_CLIENT_ID` was set twice. I'm assuming this is the problem so I'm closing this but feel free to reopen if that's not the case.

Oh my bad, I duplicated the client id twice when writing this issue, which is not the case I edit the original issue 😅

**Comment by thamudi** [comment] 2024-01-16 11:38
Can you please re-open the issue, it seems I cant open it.

**Comment by thamudi** [comment] 2024-01-17 12:21
@lukevella @sjthiessen 
Here's a screenshot of the values from the env running in the container.

![image](https://github.com/lukevella/rallly/assets/18720062/4b990da1-acdc-4a81-a4bc-b810955b8005)

**Comment by lukevella** [comment] 2024-01-17 14:56
I'd prefer not to reopen the issue as it's unlikely that this is a bug in the repo. This feature has been pretty well tested. There are only two possibilities as far as I know for the OIDC login button not to appear.

1. You're missing one or more of the following env vars: `OIDC_CLIENT_ID`, `OIDC_CLIENT_SECRET`, `OIDC_DISCOVER_URL`
2. You are running an older version of Rallly

The code is pretty straight forward for enabling OIDC. If you're not seeing the button, I have to assume that the issue is one of the above.

https://github.com/lukevella/rallly/blob/c2fc3a5fac1c011f7b228c642166d7e4faa8b7a3/apps/web/src/utils/constants.ts#L16-L20

Hope this helps.

**Comment by thamudi** [comment] 2024-01-18 07:36
I just checked again and it seems that the image was still at v3.1. Just upgraded it and it ran perfectly fine.
Thanks for the support!
