### ISSUE TITLE
'New participant' pop-up not dismissed when "Submit" is clicked.

### ISSUE THREAD

**Issue by geozeke** [lukevella/rallly#1127] opened 2024-05-28 19:42 UTC
**Describe the bug**
When a new user attempts to participate in a poll, the `New Participant` pop-up is not dismissed when clicking on the `Submit` button. The circular arrow animation on the `Submit` button spins indefinitely (see image). If I manually close the pop-up ('x' on the top right), or refresh the browser window, the user's selections for the poll are actually saved properly, it's just that the pop-up window "hangs" when clicking on `Submit`.

**To Reproduce**

1. Create a new poll
2. Share the link
3. Use the link to participate in the poll as an anonymous (no login) user
4. Choose times, and enter a name
5. Attempt to submit by clicking the `Submit` button

**Expected behavior**
The `New Participant` pop-up should close when the `Submit` button is clicked and the user's preferences are recorded.

**Screenshots**
<img width="336" alt="image" src="https://github.com/lukevella/rallly/assets/22012383/d5bf0f08-409f-4589-9d3c-8335c0792302">

**Desktop (please complete the following information):**

- OS: macOS (14.5), iOS (17.5.1), Ubuntu(24.04)
- Browser Safari (macOS + iOS), Chrome (iOS), FireFox (Ubuntu) 

**Smartphone (please complete the following information):**

- Device: iPhone 15 Pro

**Comment by lukevella** [comment] 2024-06-04 12:24
Assuming this is on a self-hosted instance, would you be able to check the server logs to see if there are any errors? My guess is the server is hanging while trying to send an email out or something similar. In the next release this would be resolved since we no longer wait for emails to be sent before resolving the request.

**Comment by geozeke** [comment] 2024-06-04 12:57
Thanks for reaching out. Yes. My instance is self-hosted (Ubuntu 22.04).

I didn't see anything in the logs that would indicate something hanging while waiting for an email. When voting on a poll I tested it by filling in an email, and not filling in an email (examples below). In both cases the popup still window hangs, but when I fill-in an email address, Rallly does properly send a "Vote Received" email as expected.

<img width="337" alt="Screenshot 2024-06-04 at 08 56 10" src="https://github.com/lukevella/rallly/assets/22012383/30273ac0-05a6-41dc-9a41-a24960494adc">
<img width="337" alt="Screenshot 2024-06-04 at 08 56 40" 
src="https://github.com/lukevella/rallly/assets/22012383/44cad045-2daa-4399-ba94-c013e8823e7d">

**Comment by Vikas-singh-0** [comment] 2024-06-06 19:12
Can this be picked up?

**Comment by lukevella** [comment] 2024-06-24 07:48
I think if it's fixed it's because the latest update does not block the request while sending an email. So not sure if it's entirely resolved but would love to hear from others who've had this issue as I've not been able to reproduce it myself.

**Comment by lukevella** [comment] 2024-07-04 09:11
I'm going to go ahead and close this. Feel free to reopen if the issue persists.

**Closed by lukevella** 2024-07-04 09:11 UTC
